//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Modals
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("Category")]
    public partial class Category
    {
        [Key]
        public long CategoryId { get; set; }
        [MaxLength(30)]
        [Column(TypeName = "NVarchar")]
        public string CategoryName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        [MaxLength(100)]
        public string CreateUse { get; set; }
    }
}
