//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Modals
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("Customer")]
    public partial class Customer
    {
        [Key]
        public long CusomerId { get; set; }
        [MaxLength(50)]
        [Column(TypeName = "NVarchar")]
        public string FirstName { get; set; }
        [MaxLength(50)]
        [Column(TypeName = "NVarchar")]
        public string LastName { get; set; }
        [MaxLength(50)]
        [Column(TypeName = "Varchar")]
        public string Email { get; set; }
        [MaxLength(20)]
        [Column(TypeName = "NVarchar")]
        public string Pass { get; set; }
        [MaxLength(50)]
        [Column(TypeName = "NVarchar")]
        public string Photo { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        [Column(TypeName = "NVarchar")]
        public string CreateUse { get; set; }
    }
}
