//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Modals
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("ImageMore")]
    public partial class ImageMore
    {
        [Key]
        public long ImgId { get; set; }
        [MaxLength(30)]
        [Column(TypeName = "NVarchar")]
        public string ImgName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        [MaxLength(30)]
        [Column(TypeName = "NVarchar")]
        public string CreateUse { get; set; }
    }
}
