//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Modals
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("OrderBill")]
    public partial class OrderBill
    {
        [Key]
        public long OrderID { get; set; }
        public Nullable<long> CustomerId { get; set; }
        [Column(TypeName ="NVarchar")]
        [MaxLength(100)]
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        [Column(TypeName = "NVarchar")]
        [MaxLength(30)]
        public string CreateUse { get; set; }
    }
}
