//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Modals
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("Product")]
    public partial class Product
    {
        [Key]
        public long ProductId { get; set; }
        [MaxLength(30)]
        public string ProductName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<long> ImgID { get; set; }
        [MaxLength(100)]
        [Column(TypeName = "NVarchar")]
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        [MaxLength(30)]
        [Column(TypeName = "NVarchar")]
        public string CreateUse { get; set; }
        public Nullable<long> CategoryId { get; set; }
    }
}
